name: Build and Push Docker image

 

on:

  push:

    branches: [ "master" ]

 

  # This is used to manually run the workflow from Github Actions page

  workflow_dispatch:

 

env:

  # Use docker.io for Docker Hub if empty

  # docker.pkg.github.com

  REGISTRY: ghcr.io

  # github.repository as <account>/<repo>

  REPOSITORY: ${{ github.repository }}

  IMAGE_NAME: ssgs

  # image tag

  IMAGE_TAG: 1.0.${{ github.run_number }}

 

jobs:

  push_to_registry:

    name: Push Docker image to GitHub Packages

    runs-on: ubuntu-latest

    permissions:

      packages: write

      contents: read

    steps:

      - name: Check out the repo

        uses: actions/checkout@v2

     

      - name: Log in to GitHub Docker Registry

        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9

        with:

          registry: ${{ env.REGISTRY }}

          username: ${{ github.actor }}

          password: ${{ secrets.GITHUB_TOKEN }}

     

      - name: Build and push Docker image

        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc

        with:

          context: .

          push: true

          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

